Gui fix
Matavilla/PythonHub pull request #19
Opened 2020-06-11 04:16 UTC by Volodimirich

2020-06-11 05:52 UTC, Matavilla commented on GUI/MainMenu.py
> +        print(vidget)
wtf

2020-06-11 05:53 UTC, Matavilla commented on GUI/MainMenu.py
> +    '''Вспомогательная функция, делает окно с параметрами'''
code style много гдн

2020-06-11 05:53 UTC, Matavilla commented on GUI/MainMenu.py
> +    MsgChaos = "Момент хаоса - время до начала хаоса"
непонятно

2020-06-11 05:53 UTC, Matavilla commented on GUI/MainMenu.py
> +    MsgPois = "Количество яда - общее количество яда на игровом поле"
не должно быть

2020-06-11 05:54 UTC, Matavilla commented on GUI/MainMenu.py
> +    MsgMeal = "Количество еды - общее количество еды на игровом поле"
тоже неправильно

2020-06-11 05:55 UTC, Matavilla commented on GUI/MainMenu.py
> +    MsgTik="Тик вселенной - время совершения одного действия"
напиши более понятно везде( будто для тупых и чтобы предложения законченные были) + точки

2020-06-11 05:56 UTC, Matavilla commented on GUI/MainMenu.py
> +    numBots1 = GenField(win, "Биом 1:", (9,0))
что за 9, 0

2020-06-11 05:56 UTC, Matavilla commented on GUI/MainMenu.py
> +    numBots1 = GenField(win, "Биом 1:", (9,0))
а, строка и сстолбец что ли?

2020-06-11 05:57 UTC, Matavilla commented on GUI/MainMenu.py
> +        messagebox.showerror("Ошибка","Имеются ошибки в параметрах")
в принципе можно наверн пофункциональнее сделать, но это прям совсем не критично

2020-06-11 13:21 UTC, Volodimirich commented on GUI/MainMenu.py
> +        print(vidget)
О дебаг забыл убрать)0)

2020-06-11 13:22 UTC, Volodimirich commented on GUI/MainMenu.py
> +    numBots1 = GenField(win, "Биом 1:", (9,0))
Да, raw 9 column 0
Просто еще есть column 4

2020-06-12 01:56 UTC, vultar150 requested changes

2020-06-12 01:56 UTC, vultar150 commented on GUI/MainMenu.py
> +    MakeWindowResizable(win, 7, 13)
7, 11 но в принципе пох, все равно ниче не поменяется вроде

2020-06-12 01:56 UTC, vultar150 commented on GUI/MainMenu.py
> -        self.AmountOfPoison = int(poison)
Из формальных параметров инита тоже надо убрать poison

2020-06-12 01:56 UTC, vultar150 commented on GUI/MainMenu.py
> +        # self.AmountOfPoison = int(poison)
Это уже не нужно вообще

2020-06-12 02:20 UTC, merged