change Field: add Bots and background color
Matavilla/PythonHub pull request #3
Opened 2020-05-16 13:43 UTC by vultar150

New branch for testing map and bots

2020-05-16 14:07 UTC, Matavilla requested changes

2020-05-16 14:07 UTC, Matavilla commented on GUI/Field.py
> +                       alive: bool = True) -> None:
code style

2020-05-16 14:07 UTC, Matavilla commented on GUI/Field.py
> +                       alive: bool = True) -> None:
+ x, y заглавными

2020-05-16 14:07 UTC, Matavilla commented on GUI/Field.py
> +        self.Bounds = pygame.Rect(x, y, size*cell_size,  size*cell_size)
code style

2020-05-16 14:07 UTC, Matavilla commented on GUI/Field.py
> +        pygame.draw.rect(screen, self.Color, self.Bounds)
не оч хорошо работу фронтеда в бекенд забирать

2020-05-16 14:07 UTC, Matavilla commented on GUI/Field.py
> +
этот класс точно тут лишний

2020-05-16 14:07 UTC, Matavilla commented on GUI/Field.py
> +
+ он не вписывается в нашу схему. Я чую некоторое непонимание в группе. Наверное надо встречу делать

2020-05-16 14:07 UTC, Matavilla commented on GUI/Field.py
> +        self.Bounds = pygame.Rect(x, y, size*cell_size,  size*cell_size)
поправь везде

2020-05-16 14:07 UTC, Matavilla commented on GUI/Field.py
> +                       tik: int) -> None:
код стайл

2020-05-16 14:07 UTC, Matavilla commented on GUI/Field.py
> +    def draw(self, screen):
надо решить как методы обзываем, а то каждый пишет как хочет. Пока вроде писали с заглавной как и все функции

2020-05-16 14:07 UTC, Matavilla commented on GUI/Field.py
> +        self.BackgroundImage = pygame.image.load(back_image_filename)
не понял смысл изображения, если у нас есть цвет клетки

2020-05-16 14:07 UTC, Matavilla commented on GUI/Field.py
> +        self.Tik = tik
класс исключительно для вывода изображения. Вован его так и не переименовал

2020-05-16 14:07 UTC, Matavilla commented on GUI/Field.py
> -                pygame.draw.rect(self.Screen, get_color(Map[hei][wei]), Rect)
Зочем, у нас же клетки

2020-05-16 14:07 UTC, Matavilla commented on GUI/Field.py
> +            self.clock.tick(self.Tik)
см класс про бота

2020-05-16 14:07 UTC, Matavilla commented on GUI/Field.py
> +        super().update()
хорошая задумка, если обозвать его как Game. в него положить функции из Tk. Засунуть объект класса Handler. Генератор карты. Но как это сделать в питоне я хз. Поэтому не понимаю зачем он нужен.

2020-05-16 14:07 UTC, Matavilla commented on GUI/Field.py
> +        super().update()
Вообще ты продублировал что должно лежать в Handler. По задумке - в handler будут лежать все массивы и все данные. Он будет возвращать в класс Game(кот должен называться как поле) массив из классы ячейка поля, которое и будет выводить. В классе хендлер по задумке есть и функция - генератор карты и метод run - который говорит что со вселенной произошло за тик.

Крч, предложение к этому коду такое:
1) вынести класс бота отсюда куда нить в src (создай какой нить адекватный путь)
2) обработку каждого бота вынести в хендлер в соответсвующий метод. ИИ мы еще не писали, поэтому можно в таком виде в котором ты написал.
3) Класс лайфхаб предлагаю убрать. Если есть желание оставить, то тогда надо серьезно перепахивать уже готовый код, потому что с ним все выглядит неопрятно.
4) Из хендлера планировалось возвращать общую карту и просто вывести ее. Этого момента у нас вообще нет. Поэтому давай твою ветку пока не мержить, а этот вывод надо бы протянуть. Но сперва еще генератор нужен + класс поля карты

2020-05-16 14:07 UTC, Matavilla commented on GUI/Field.py
> +        super().update()
1,2 надо бы запушить

2020-05-16 14:07 UTC, Matavilla commented on GUI/Field.py
> +        super().update()
3 надо решить совместно

2020-05-16 14:07 UTC, Matavilla commented on GUI/Field.py
> +        super().update()
а 4 написать, но тут сначала как вова свое исправит и зальет

2020-06-05 19:35 UTC, merged

2020-06-05 19:44 UTC, Matavilla commented on GUI/Field.py
> +import sys
давай эту херню уберем

2020-06-05 19:44 UTC, Matavilla commented on GUI/MainMenu.py
> +
и png файл

2020-06-05 19:45 UTC, Matavilla commented on src/Handler.py
> +	def __init__(self, worldPar):
я чет не понял у кого из нас отступы не правильные?

2020-06-05 19:45 UTC, Matavilla commented on src/Handler.py
> +			while self.Map.Field[x][y].is_bot_here() or self.Map.Field[x][y].is_food_here():
зациклишься если все клетки использованы.

2020-06-05 19:47 UTC, Matavilla commented on src/Handler.py
> +				if self.Map.Field[x][y].is_bot_here():
заведи лучше массив с координатами ботов. Проще ж будет

2020-06-05 19:48 UTC, Matavilla commented on src/Handler.py
> -        self.Tick += 1
не понял прикола. Зачем еду убрал?

2020-06-05 19:48 UTC, Matavilla commented on src/bot/Bot.py
> +        self.Color = ((self.Bot_value * 3) % 256, (self.Bot_value * 4) % 256, 100)
с едой не сливаются?

2020-06-05 19:49 UTC, Matavilla commented on src/dna/Dna.py
> +        self.Gens = array.array('H')
надо тогда 8 байт использовать, а то получать бит на 15 позици не оч хочется

2020-06-05 19:50 UTC, Matavilla commented on src/dna/Dna.py
> +            self.set_value("armor", random.randint(10, 15))
надо тогда как то нам интерпретировать эти параметры с 256 возможными значениями, которые могут в геноме возникнуть

2020-06-05 19:51 UTC, vultar150 commented on src/Handler.py
> -        self.Tick += 1
Закоментил, чтобы протестить. Очень быстро заполоняет всю карту

2020-06-05 19:51 UTC, vultar150 commented on src/bot/Bot.py
> +        self.Color = ((self.Bot_value * 3) % 256, (self.Bot_value * 4) % 256, 100)
Сливаются немного, цета исправлю

2020-06-05 19:52 UTC, vultar150 commented on src/dna/Dna.py
> +        self.Gens = array.array('H')
До генетического пока не дошел

2020-06-05 19:54 UTC, vultar150 commented on GUI/MainMenu.py
> +
убрал

2020-06-05 19:55 UTC, vultar150 commented on GUI/Field.py
> +import sys
убрал

2020-06-05 19:59 UTC, vultar150 commented on src/Handler.py
> +			while self.Map.Field[x][y].is_bot_here() or self.Map.Field[x][y].is_food_here():
По поводу всех клеток, кол-во еды + кол-во ботов надо как то либо ограничить еще сильнее, или же добавить возможность генерации новой еды на старой, ну или же 3 вариант проверять занят ли весь биом, и не добавлять просто

2020-06-05 20:00 UTC, vultar150 commented on src/Handler.py
> +				if self.Map.Field[x][y].is_bot_here():
заведу

2020-06-05 21:51 UTC, vultar150 commented on src/Handler.py
> +	def __init__(self, worldPar):
исправил

2020-06-05 21:51 UTC, vultar150 commented on src/Handler.py
> +			while self.Map.Field[x][y].is_bot_here() or self.Map.Field[x][y].is_food_here():
исправил

2020-06-05 21:51 UTC, vultar150 commented on src/Handler.py
> +				if self.Map.Field[x][y].is_bot_here():
сделано

2020-06-05 21:51 UTC, vultar150 commented on src/bot/Bot.py
> +        self.Color = ((self.Bot_value * 3) % 256, (self.Bot_value * 4) % 256, 100)
исправлено